# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-09 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField()),
                ('password', models.TextField()),
            ],
            options={
                'db_table': 'admin',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Anheuserbusch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talent', models.TextField()),
                ('client', models.TextField()),
                ('gender', models.TextField()),
                ('age_range', models.TextField()),
                ('language', models.TextField()),
                ('sample_url', models.TextField()),
                ('accepted', models.TextField()),
                ('comment', models.TextField()),
            ],
            options={
                'db_table': 'anheuserbusch',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Apple',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talent', models.TextField()),
                ('client', models.TextField()),
                ('gender', models.TextField()),
                ('age_range', models.TextField()),
                ('language', models.TextField()),
                ('sample_url', models.TextField()),
                ('accepted', models.TextField()),
                ('comment', models.TextField()),
            ],
            options={
                'verbose_name': 'The Force',
                'db_table': 'apple',
                'managed': True,
                'verbose_name_plural': 'The Force',
            },
        ),
        migrations.CreateModel(
            name='Cisco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talent', models.TextField()),
                ('client', models.TextField()),
                ('gender', models.TextField()),
                ('age_range', models.TextField()),
                ('language', models.TextField()),
                ('sample_url', models.TextField()),
                ('accepted', models.TextField()),
                ('comment', models.TextField()),
            ],
            options={
                'db_table': 'cisco',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('username', models.TextField()),
                ('password', models.TextField()),
            ],
            options={
                'db_table': 'client',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Esterline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talent', models.TextField()),
                ('client', models.TextField()),
                ('gender', models.TextField()),
                ('age_range', models.TextField()),
                ('language', models.TextField()),
                ('sample_url', models.TextField()),
                ('accepted', models.TextField()),
                ('comment', models.TextField()),
            ],
            options={
                'db_table': 'esterline',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Google',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talent', models.TextField()),
                ('client', models.TextField()),
                ('gender', models.TextField()),
                ('age_range', models.TextField()),
                ('language', models.TextField()),
                ('sample_url', models.TextField()),
                ('accepted', models.TextField()),
                ('comment', models.TextField()),
            ],
            options={
                'db_table': 'google',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Gt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talent', models.TextField()),
                ('client', models.TextField()),
                ('gender', models.TextField()),
                ('age_range', models.TextField()),
                ('language', models.TextField()),
                ('sample_url', models.TextField()),
                ('accepted', models.TextField()),
                ('comment', models.TextField()),
            ],
            options={
                'db_table': 'gt',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Hd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talent', models.TextField()),
                ('client', models.TextField()),
                ('gender', models.TextField()),
                ('age_range', models.TextField()),
                ('language', models.TextField()),
                ('sample_url', models.TextField()),
                ('accepted', models.TextField()),
                ('comment', models.TextField()),
            ],
            options={
                'db_table': 'hd',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Jdeere',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talent', models.TextField()),
                ('client', models.TextField()),
                ('gender', models.TextField()),
                ('age_range', models.TextField()),
                ('language', models.TextField()),
                ('sample_url', models.TextField()),
                ('accepted', models.TextField()),
                ('comment', models.TextField()),
            ],
            options={
                'db_table': 'jdeere',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Kornferry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talent', models.TextField()),
                ('client', models.TextField()),
                ('gender', models.TextField()),
                ('age_range', models.TextField()),
                ('language', models.TextField()),
                ('sample_url', models.TextField()),
                ('accepted', models.TextField()),
                ('comment', models.TextField()),
            ],
            options={
                'db_table': 'kornferry',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.TextField()),
            ],
            options={
                'db_table': 'language',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Main',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talent', models.TextField()),
                ('client', models.TextField()),
                ('gender', models.TextField()),
                ('age_range', models.TextField()),
                ('language', models.TextField()),
                ('sample_url', models.TextField()),
                ('accepted', models.TextField()),
                ('comment', models.TextField()),
            ],
            options={
                'verbose_name': 'Main Talent',
                'db_table': 'main',
                'managed': True,
                'verbose_name_plural': 'Main Talents',
            },
        ),
        migrations.CreateModel(
            name='Nrm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talent', models.TextField()),
                ('client', models.TextField()),
                ('gender', models.TextField()),
                ('age_range', models.TextField()),
                ('language', models.TextField()),
                ('sample_url', models.TextField()),
                ('accepted', models.TextField()),
                ('comment', models.TextField()),
            ],
            options={
                'db_table': 'nrm',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Resaas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talent', models.TextField()),
                ('client', models.TextField()),
                ('gender', models.TextField()),
                ('age_range', models.TextField()),
                ('language', models.TextField()),
                ('sample_url', models.TextField()),
                ('accepted', models.TextField()),
                ('comment', models.TextField()),
            ],
            options={
                'verbose_name': 'Resaas',
                'db_table': 'resaas',
                'managed': True,
                'verbose_name_plural': 'Resaas',
            },
        ),
        migrations.CreateModel(
            name='Talent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('welo_id', models.TextField()),
                ('vendor_id', models.TextField()),
                ('vendor_name', models.TextField()),
                ('gender', models.TextField()),
                ('age_range', models.TextField()),
                ('language', models.TextField()),
                ('sample_url', models.TextField()),
                ('pre_approved', models.TextField()),
                ('comment', models.TextField()),
                ('allclients', models.TextField()),
                ('vmware', models.TextField()),
                ('google', models.TextField()),
                ('gt', models.TextField()),
                ('nrm', models.TextField()),
                ('hr', models.TextField()),
                ('rate', models.TextField()),
                ('hd', models.TextField()),
                ('workday', models.TextField()),
                ('tts', models.TextField()),
                ('cisco', models.TextField()),
                ('kornferry', models.TextField()),
                ('jdeere', models.TextField()),
                ('anheuserbusch', models.TextField()),
                ('apple', models.TextField()),
                ('thomsonreuters', models.TextField()),
                ('esterline', models.TextField()),
            ],
            options={
                'db_table': 'talent',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Thomsonreuters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talent', models.TextField()),
                ('client', models.TextField()),
                ('gender', models.TextField()),
                ('age_range', models.TextField()),
                ('language', models.TextField()),
                ('sample_url', models.TextField()),
                ('accepted', models.TextField()),
                ('comment', models.TextField()),
            ],
            options={
                'db_table': 'thomsonreuters',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('username', models.TextField()),
                ('password', models.TextField()),
            ],
            options={
                'db_table': 'vendor',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Vmware',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talent', models.TextField()),
                ('client', models.TextField()),
                ('gender', models.TextField()),
                ('age_range', models.TextField()),
                ('language', models.TextField()),
                ('sample_url', models.TextField()),
                ('accepted', models.TextField()),
                ('comment', models.TextField()),
            ],
            options={
                'db_table': 'vmware',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Workday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talent', models.TextField()),
                ('client', models.TextField()),
                ('gender', models.TextField()),
                ('age_range', models.TextField()),
                ('language', models.TextField()),
                ('sample_url', models.TextField()),
                ('accepted', models.TextField()),
                ('comment', models.TextField()),
            ],
            options={
                'db_table': 'workday',
                'managed': True,
            },
        ),
    ]
