# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-08 19:31
from __future__ import unicode_literals

import choices.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('username', models.TextField()),
                ('logo', models.FileField(blank=True, null=True, upload_to='client_logos', validators=[choices.validators.validate_imagefile_extension])),
            ],
            options={
                'ordering': ['name'],
                'db_table': 'client',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('approved_comment', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.TextField()),
            ],
            options={
                'ordering': ['language'],
                'db_table': 'language',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Selection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PREAPPROVED', 'Pre_Approved'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PREAPPROVED', max_length=16)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='choices.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Talent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('PRO', 'Pro Recording'), ('HR', 'Home Recording'), ('TTS', 'Text To Speech')], default='PR0', max_length=16, null=True)),
                ('welo_id', models.TextField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Undeclared')], default='U', max_length=32)),
                ('age_range', models.CharField(choices=[('1-15', '1-15'), ('16-25', '16-25'), ('26-45', '26-45'), ('46-75', '46-75'), ('75 +', '75 +')], default='26-45', max_length=32)),
                ('comment', models.TextField(blank=True, null=True)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to=b'', validators=[choices.validators.validate_audiofile_extension])),
                ('rate', models.TextField(blank=True, null=True)),
                ('average_rating', models.IntegerField(blank=True, null=True)),
                ('language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='choices.Language')),
            ],
            options={
                'ordering': ['welo_id'],
                'db_table': 'talent',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='choices.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('username', models.TextField()),
            ],
            options={
                'ordering': ['name'],
                'db_table': 'vendor',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='choices.Vendor'),
        ),
        migrations.AddField(
            model_name='talent',
            name='vendor',
            field=models.ForeignKey(blank=True, default=9, null=True, on_delete=django.db.models.deletion.CASCADE, to='choices.Vendor'),
        ),
        migrations.AddField(
            model_name='selection',
            name='talent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='choices.Talent'),
        ),
        migrations.AddField(
            model_name='rating',
            name='rater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rating',
            name='talent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='choices.Talent'),
        ),
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='selection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='choices.Selection'),
        ),
        migrations.AlterUniqueTogether(
            name='selection',
            unique_together=set([('talent', 'client')]),
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together=set([('talent', 'rater')]),
        ),
    ]
