# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-09 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='talents',
            field=models.ManyToManyField(to='choices.Talent'),
        ),
    ]
