# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-16 01:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='talent',
            name='audio_file_sha',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
