# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-09 18:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('choices', '0002_client_talents'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'managed': True, 'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='talent',
            options={'managed': True, 'ordering': ['welo_id']},
        ),
        migrations.AddField(
            model_name='talent',
            name='vendor_fk',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, to='choices.Vendor'),
        ),
    ]
