# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-16 20:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choices', '0002_talent_audio_file_sha'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('audio_files', models.FileField(upload_to=b'')),
            ],
        ),
    ]
