# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-09 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choices', '0003_auto_20160909_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talent',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
