# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-17 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choices', '0004_auto_20170116_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='code',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='upload',
            name='audio_files',
            field=models.FileField(upload_to='bulk_upload/'),
        ),
    ]
