# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-11 00:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choices', '0005_auto_20160910_2324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='status',
            name='pre_approved',
        ),
        migrations.RemoveField(
            model_name='status',
            name='rejected',
        ),
        migrations.AddField(
            model_name='status',
            name='status',
            field=models.CharField(choices=[('PREAPPROVED', 'Pre_Approved'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PREAPPROVED', max_length=16),
        ),
    ]
