# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-11 00:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choices', '0006_auto_20160911_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selection',
            name='status',
            field=models.CharField(choices=[('PREAPPROVED', 'Pre_Approved'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PREAPPROVED', max_length=16),
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
