# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-12 21:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('choices', '0007_auto_20160911_0006'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='selection',
            unique_together=set([('talent', 'client')]),
        ),
    ]
