# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-28 00:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('choices', '0007_auto_20170126_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='talent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='talent',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='language',
            name='code',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='talent',
            name='type',
            field=models.CharField(choices=[('PRO', 'Pro Recording'), ('HR', 'Home Recording'), ('TTS', 'Text To Speech')], default='PR0', max_length=16, null=True),
        ),
    ]
