# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-28 18:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('choices', '0008_auto_20170128_0035'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Upload',
        ),
    ]
