# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-02 03:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('choices', '0009_delete_upload'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TalentsByVendor',
        ),
    ]
