# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-12 23:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('choices', '0009_remove_talent_vendor_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='talents',
        ),
    ]
