# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-18 19:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('choices', '0013_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='talent',
            name='times_rated',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='talent',
            name='total_rating',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='talent',
            name='rate',
            field=models.TextField(blank=True, null=True),
        ),
    ]
