# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-15 01:18
from __future__ import unicode_literals

import audiofield.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choices', '0013_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='talent',
            name='audio_file',
            field=audiofield.fields.AudioField(blank=True, help_text='Allowed type - .mp3, .wav, .ogg', upload_to='your/upload/dir'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 15, 1, 18, 36, 796097)),
        ),
    ]
