# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-19 13:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('choices', '0014_auto_20160918_1937'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(blank=True, default=0, null=True)),
                ('rater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='choices.UserProfile')),
                ('talent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='choices.Talent')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together=set([('talent', 'rater')]),
        ),
    ]
