# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-19 20:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choices', '0015_auto_20160919_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='talent',
            name='audio_file',
            field=models.FileField(blank=True, upload_to=b''),
        ),
    ]
