# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-20 15:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('choices', '0017_auto_20160920_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='talent',
            name='vt_vendor',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, to='choices.Vendor'),
        ),
    ]
