# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-20 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choices', '0018_talent_vt_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='vendor_id',
            field=models.TextField(default='TBD'),
        ),
    ]
