# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-20 17:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('choices', '0019_vendor_vendor_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vendor',
            options={'managed': True, 'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='vendor_id',
        ),
    ]
