# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-20 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choices', '0020_auto_20160920_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='talent',
            name='type',
            field=models.CharField(choices=[('PRO', 'Pro Recording'), ('HR', 'Home Recording'), ('TTS', 'Text To Speech')], default='PR0', max_length=16),
        ),
    ]
