# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-22 20:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choices', '0021_talent_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='talent',
            name='utc',
            field=models.TextField(default='n'),
            preserve_default=False,
        ),
    ]
