# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-23 18:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('choices', '0022_talent_utc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='talent',
            name='vendor_id',
        ),
        migrations.RemoveField(
            model_name='talent',
            name='vendor_name',
        ),
        migrations.AlterField(
            model_name='talent',
            name='vt_vendor',
            field=models.ForeignKey(blank=True, default=9, null=True, on_delete=django.db.models.deletion.CASCADE, to='choices.Vendor'),
        ),
    ]
