# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-23 18:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('choices', '0023_auto_20160923_1804'),
    ]

    operations = [
        migrations.RenameField(
            model_name='talent',
            old_name='vt_vendor',
            new_name='vendor',
        ),
    ]
