# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-24 22:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choices', '0024_auto_20160923_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='talent',
            name='old_talent_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
