# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choices', '0025_talent_old_talent_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='talent',
            name='anheuserbusch',
        ),
        migrations.RemoveField(
            model_name='talent',
            name='apple',
        ),
        migrations.RemoveField(
            model_name='talent',
            name='cisco',
        ),
        migrations.RemoveField(
            model_name='talent',
            name='esterline',
        ),
        migrations.RemoveField(
            model_name='talent',
            name='google',
        ),
        migrations.RemoveField(
            model_name='talent',
            name='gt',
        ),
        migrations.RemoveField(
            model_name='talent',
            name='hd',
        ),
        migrations.RemoveField(
            model_name='talent',
            name='hr',
        ),
        migrations.RemoveField(
            model_name='talent',
            name='jdeere',
        ),
        migrations.RemoveField(
            model_name='talent',
            name='kornferry',
        ),
        migrations.RemoveField(
            model_name='talent',
            name='nrm',
        ),
        migrations.RemoveField(
            model_name='talent',
            name='pre_approved',
        ),
        migrations.RemoveField(
            model_name='talent',
            name='thomsonreuters',
        ),
        migrations.RemoveField(
            model_name='talent',
            name='tts',
        ),
        migrations.RemoveField(
            model_name='talent',
            name='utc',
        ),
        migrations.RemoveField(
            model_name='talent',
            name='vmware',
        ),
        migrations.RemoveField(
            model_name='talent',
            name='workday',
        ),
        migrations.AlterField(
            model_name='talent',
            name='age_range',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='talent',
            name='allclients',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='talent',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='talent',
            name='gender',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='talent',
            name='language',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='talent',
            name='sample_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='talent',
            name='type',
            field=models.CharField(blank=True, choices=[('PRO', 'Pro Recording'), ('HR', 'Home Recording'), ('TTS', 'Text To Speech')], default='PR0', max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='talent',
            name='welo_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
