# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 16:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('choices', '0026_auto_20160929_1520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='talent',
            name='sample_url',
        ),
    ]
