# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 19:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('choices', '0027_remove_talent_sample_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talent',
            name='age_range',
            field=models.CharField(blank=True, choices=[(1, '1 - 15'), (2, '16 - 25'), (3, '26 - 45'), (4, '46 - 75'), (5, '75 +')], default=1, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='talent',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Undeclared')], default=1, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='talent',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='choices.Language'),
        ),
    ]
