# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-30 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choices', '0028_auto_20160929_1902'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='language',
            options={'managed': True, 'ordering': ['language']},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['user__username']},
        ),
        migrations.AlterField(
            model_name='talent',
            name='age_range',
            field=models.CharField(blank=True, choices=[('1', '1-15'), ('2', '16-25'), ('3', '26-45'), ('4', '46-75'), ('5', '75 +')], default=3, max_length=32, null=True),
        ),
    ]
