# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-30 19:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('choices', '0029_auto_20160930_1530'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Anheuserbusch',
        ),
        migrations.DeleteModel(
            name='Apple',
        ),
        migrations.DeleteModel(
            name='Cisco',
        ),
        migrations.DeleteModel(
            name='Esterline',
        ),
        migrations.DeleteModel(
            name='Google',
        ),
        migrations.DeleteModel(
            name='Gt',
        ),
        migrations.DeleteModel(
            name='Hd',
        ),
        migrations.DeleteModel(
            name='Jdeere',
        ),
        migrations.DeleteModel(
            name='Kornferry',
        ),
        migrations.DeleteModel(
            name='Main',
        ),
        migrations.DeleteModel(
            name='Nrm',
        ),
        migrations.DeleteModel(
            name='Resaas',
        ),
        migrations.DeleteModel(
            name='Thomsonreuters',
        ),
        migrations.DeleteModel(
            name='Vmware',
        ),
        migrations.DeleteModel(
            name='Workday',
        ),
    ]
