# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-30 20:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choices', '0030_auto_20160930_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='last_modified',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='selection',
            name='last_modified',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
