# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-07 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choices', '0034_auto_20161005_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='client_logos'),
        ),
    ]
