# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-07 17:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('choices', '0035_client_logo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='selection',
        ),
    ]
