# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-12 19:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('choices', '0038_remove_client_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='password',
        ),
    ]
