# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-12 20:59
from __future__ import unicode_literals

import choices.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('choices', '0039_remove_vendor_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='client_logos', validators=[choices.validators.validate_imagefile_extension]),
        ),
        migrations.AlterField(
            model_name='talent',
            name='age_range',
            field=models.CharField(choices=[('1-15', '1-15'), ('16-25', '16-25'), ('26-45', '26-45'), ('46-75', '46-75'), ('75 +', '75 +')], default='26-45', max_length=32),
        ),
        migrations.AlterField(
            model_name='talent',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to=b'', validators=[choices.validators.validate_audiofile_extension]),
        ),
        migrations.AlterField(
            model_name='talent',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Undeclared')], default='U', max_length=32),
        ),
        migrations.AlterField(
            model_name='talent',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='choices.Language'),
        ),
    ]
