# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-26 15:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('choices', '0040_auto_20161012_2059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='talent',
            name='times_rated',
        ),
        migrations.RemoveField(
            model_name='talent',
            name='total_rating',
        ),
    ]
