# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-26 15:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('choices', '0041_auto_20161026_1501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='talent',
            name='old_talent_id',
        ),
    ]
