# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-26 20:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choices', '0042_remove_talent_old_talent_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='talent',
            name='average_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
