# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-26 20:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choices', '0043_talent_average_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='talent',
            name='times_accepted',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='talent',
            name='times_rejected',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
