# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-27 17:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('choices', '0044_auto_20161026_2035'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={},
        ),
    ]
