# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-28 13:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('choices', '0045_auto_20161027_1742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='talent',
            name='times_accepted',
        ),
        migrations.RemoveField(
            model_name='talent',
            name='times_rejected',
        ),
    ]
